docs_dir: docs

site_name: POVME
site_author: durrantlab

# Git host
repo_name: durrantlab/POVME
repo_url: https://github.com/durrantlab/POVME

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - toc.follow
    - search.suggest

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Options need to be indented twice for some reason?
plugins:
  - search
  - autorefs
  - material-plausible
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: ["povme"]
          options:
            show_source: false
            show_root_heading: false
            annotations_path: brief
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: spacy
            show_if_no_docstring: true
  - awesome-pages:
        collapse_single_pages: true
        strict: false
        order: asc
        sort_type: natural
        order_by: title
  - git-revision-date-localized:
      type: iso_datetime
      timezone: America/Detroit
      fallback_to_build_date: true
  - macros
  - table-reader
  - glightbox
  - mkdocs-jupyter:
        no_input: False
        include_requirejs: true
        include_source: True
        ignore: ["*.py"]
        remove_tag_config:
            remove_input_tags:
                - hide_code

hooks:
  - hooks/launchy.py
colab_base_url: https://colab.research.google.com/github/durrantlab/POVME/blob/main/docs

extra:
  generator: true
  # analytics:
  #   provider: plausible
  #   domain: povme
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/durrantlab
      name: Durrant Lab on GitHub

extra_css:
  - css/base.css
  - css/colors.css
  - css/mkdocstrings.css
  - css/launchy.css
  - css/jupyter.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - js/mathjax-config.js

markdown_extensions:
  - abbr
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
