[project]
authors = ["Jacob Durrant <durrantj@pitt.edu>"]
channels = ["conda-forge"]
description = "Detect and characterize pockets from molecular simulations"
name = "povme"
platforms = ["linux-64"]
version = "2.2.1"
readme = "README.md"

[pypi-dependencies]
povme = { path = ".", editable = true }
pymolecule = { git = "https://github.com/durrantlab/pymolecule.git", rev = "121c34103169d362f4ed2ca9207dd5555f9dc25b" }
ray = { version = ">=2.37.0,<3"}

[system-requirements]
linux = "3.10.0"
libc = { family="glibc", version="2.17" }

[tasks]

[environments]
dev = ["dev"]
docs = ["docs"]

[dependencies]
python = ">=3.10,<3.13"
scipy = ">=1.14.1,<2"
numpy = ">=2.1.3,<3"
pydantic = ">=2.10.2,<3"
pyyaml = ">=6.0.2,<7"
loguru = ">=0.7.2,<0.8"

[feature.dev.dependencies]
ruff = ">=0.7.2,<0.8"
black = ">=24.10.0,<25"
isort = ">=5.13.2,<6"
mypy = ">=1.13.0,<2"
twine = ">=5.1.1,<6"
bump-my-version = ">=0.28.1,<0.29"
pytest = ">=8.3.3,<9"
pytest-cov = ">=6.0.0,<7"
coverage = ">=7.6.4,<8"
pip = ">=24.3.1,<25"
setuptools = ">=75.3.0,<76"
types-pyyaml = ">=6.0.12.20240917,<7"
scalene = ">=1.5.41,<2"

[feature.dev.tasks]
mdlint = { cmd = ["markdownlint-cli2", '"**/*.{md,markdown}"', "--fix", "--config", ".markdownlint.yaml", "||", "true"] }
isort = { cmd = ["isort", "--settings-path", ".isort.cfg", "./povme", "./tests", "||", "true"] }
black = { cmd = ["black", "--config", ".black.toml", "./povme", "./tests", "||", "true"] }
format = { depends-on = ["mdlint", "isort", "black"] }
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='povme'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
profile = { cmd = [
    "PYTHONPATH=.",
    "scalene",
    "-m",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='povme'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
coverage = { cmd = ["coverage", "report"] }
cleanup-build = { cmd = ["rm", "-rf", "./build"] }
build = { cmd = ["python3", "-m", "build"], depends-on = ["cleanup-build"]}
publish-test = { cmd = ["twine", "upload", "--repository", "testpypi", "dist/*"] }
publish = { cmd = ["twine", "upload", "dist/*"] }

[feature.dev.pypi-dependencies]
build = ">=1.2.2.post1,<2"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.5.44,<10"
pymdown-extensions = ">=10.12,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocstrings = ">=0.26.2,<0.27"
mkdocstrings-python = ">=1.12.2,<2"
mkdocs-gen-files = ">=0.4.0,<0.5"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-jupyter = ">=0.25.0,<0.26"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"
mkdocs-autorefs = ">=1.2.0,<2"

[feature.docs.pypi-dependencies]
material-plausible-plugin = ">=0.2.0,<0.3"
mkdocs-awesome-pages-plugin = ">=2.9.3,<3"

[feature.docs.tasks]
docs = { cmd = ["rm", "-rf", "./public/", "&&", "mkdocs", "build", "-d", "public/"] }
serve-docs = { cmd = ["mkdocs", "serve"] }
